[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent for interactive elements
primaryColor="#E7D2CC"

# Background color for the main content area
backgroundColor="#868B8E"
# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#B9B7BD"

# Color used for almost all text
textColor="#EEEDE7"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font="sans serif"
